name: trips_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  intl: ^0.20.2
  equatable: ^2.0.7
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.2
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0
  flutter_gen_runner: ^5.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/images/
    - trips_mock.json

flutter_gen:
  output: lib/app/core/constants/
  line_length: 100
  integrations:
    flutter_svg: true